# Generated by Django 2.2.13 on 2020-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
