# Generated by Django 2.2.13 on 2020-10-09 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201008_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='posti', to=settings.AUTH_USER_MODEL),
        ),
    ]
