# Generated by Django 2.2.13 on 2020-10-10 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201010_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, default=None, related_name='follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
