# Generated by Django 2.2.13 on 2020-10-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201011_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilei',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profilei',
            name='follower',
        ),
        migrations.AddField(
            model_name='profilei',
            name='follower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profilei',
            name='following',
        ),
        migrations.AddField(
            model_name='profilei',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
