# Generated by Django 2.2.13 on 2020-10-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_profilei_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilei',
            name='user',
        ),
    ]
