# Generated by Django 2.2.13 on 2020-10-13 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20201014_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followe',
            field=models.ManyToManyField(blank=True, related_name='ufollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
