# Generated by Django 2.2.13 on 2020-10-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_user_followe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilei',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
