# Generated by Django 2.2.13 on 2020-10-14 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_profilei_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilei',
            name='user',
        ),
        migrations.AddField(
            model_name='profilei',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='dsds', to=settings.AUTH_USER_MODEL),
        ),
    ]
