# Generated by Django 2.2.13 on 2020-11-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
